### ISSUE TITLE
hash("key2") % 8 is 2!

### ISSUE THREAD

**Issue by lucomsky** [zpoint/CPython-Internals#47]
You have a mistake here...

> Whenever you search for an element or insert a new element, according to the value of hash result mod the size of indices, you can get an index in the indices array, and get the result you want from the entries according to the newly get index, For example, the result of hash("key2") % 8 is 3, and the value in indices[3] is 1, so we can go to entries and find what we need in entries[1]

**Comment by zpoint** [comment]
It's an example, and I don't think it's a mistake

The Python Interpreter will generate a new hash seed every time you start it

The following code will have different output If you quit the interpreter, and start a new one

```python3
print("key2".__hash__())
quit() 
```

Since the hash result is different, `hash("key2") % 8` will also be different

> .IP PYTHONHASHSEED
If this variable is set to "random", a random value is used to seed the hashes
of str, bytes and datetime objects.

> If PYTHONHASHSEED is set to an integer value, it is used as a fixed seed for
generating the hash() of the types covered by the hash randomization.  Its
purpose is to allow repeatable hashing, such as for selftests for the
interpreter itself, or to allow a cluster of python processes to share hash
values.


see `_Py_HashRandomization_Init` defined in `cpython/Python/bootstrap_hash.c`

**Comment by lucomsky** [comment]
You are right! Thanks for clarification! 🙂

**Comment by hfudev** [comment]
good to know about `PYTHONHASHSEED`
